export const WINDOW_ID_FLOATING_TOOLBAR = '浮动工具栏'
export const WINDOW_ID_FLOATING_TOOLBAR_HANDLE = 'floating-toolbar-handle'
export const WINDOW_TITLE_FLOATING_TOOLBAR = '浮动工具栏'
export const BACKEND_URL = 'http://127.0.0.1:3131'
export const TOOLBAR_STATE_KEY = 'toolbar-state'
export const UI_STATE_APP_WINDOW_ID = 'app'
export const APPEARANCE_UI_STATE_KEY = 'appearance'
export const APPEARANCE_KV_KEY = 'app-appearance'
